export const SYSTEM_PROMPT = "We will be doing classic text-based dungeon-crawl set in roleplaying worlds. I will provide a prompt with a world, a writing style,  a setting, and a goal. Refer to the player in second person.\r\n\r\nAfter each step, I will tell you the player's next choice. I will also tell you whether the player should die or win on the next encounter.\r\n\r\nPlease respond in two separate sections, marked by keywords.\r\n\r\nAfter the keyword \"text:\", please describe the room or situation, and if applicable, what happened after the player action. Use around 150 words. Actively introduce new events that are appropriate, such as unexpected or negative outcomes, intruders or discoveries, betrayal by NPCs, and so on.\r\n\r\nThen after the keyword \"options:\"\r\nOffer a set of 4 numbered options on what to do next. Use around 7 words for each option. After each option, add a number between (1) and (5) indicating how risky the option is, with 5 as the maximum. Avoid generating options that involve waiting, asking for more information, looking around, etc. Wait for the player to choose one of them, after which you generate the next room.\r\n"

export const UNIVERSES = [
  "Forgotten Realms",
  "Greyhawk",
  "Dragonlance",
  "Eberron",
  "Planescape",
  "Ravenloft",
  "Dark Sun",
  "Mystara",
  "Spelljammer",
  "Warhammer 40k",
  "Warhammer Fantasy",
  "Shadowrun",
  "Star Wars Roleplaying",
  "Numenera",
  "Eclipse Phase",
  "Firefly (Cortex System)"
];

export const ADJECTIVES = [
  "Bustling",
  "Eerie",
  "Intimidating",
  "Majestic",
  "Serene",
  "Mystical",
  "Dystopian",
  "Otherworldly",
  "Lush",
  "Ancient",
  "Mysterious",
  "Ruined",
  "Vibrant",
  "Whimsical",
  "Haunted",
  "Secluded",
  "Industrial",
  "Abandoned",
  "Futuristic",
  "Cursed",
  "Overgrown"
];

export const LOCATIONS = [
  "Great Tree",
  "Stronghold",
  "Academy",
  "Cave",
  "Manor",
  "Labyrinth",
  "Restaurant",
  "City",
  "Megacity",
  "Castle",
  "Shop",
  "Forest",
  "Portal",
  "Island",
  "Floating Island",
  "Ritual Site",
  "Temple",
  "Ship",
  "Suburb",
  "Small Settlement",
  "Swamp",
  "Mountain",
  "Hellscape",
  "Forge",
  "Underwater Cave",
  "Market",
  "Wasteland",
  "Shipwreck",
  "Tavern"
];

export const PERSONS = [
  "Thalorin",
  "Elowyn",
  "Kael'Tarim",
  "Dornak",
  "Isolde",
  "Zephyrion",
  "Grimgar",
  "Googoo",
  "Arkanor",
  "Lirael",
  "Azurin",
  "Drak'Morak",
  "Evadryn",
  "Tethralin",
  "Valandor",
  "Punchman",
  "Zephyria",
  "Daerys",
  "Aeloria",
  "Vyndara",
  "Caelithor",
  "Grommash",
  "Snarlag",
  "Grokthar",
  "Krulmok",
  "Griznok",
  "Ugluk",
  "Morglug",
  "Brakthorn",
  "Zogrek",
  "Thrakka",
  "Xyleron",
  "Novastra",
  "Zephyrus IX",
  "Mufasa",
  "Quantumix",
  "Nebulon",
  "Threnox",
  "ExoVox",
  "Zytron-7",
  "Astridium",
  "Helixar",
  "Cybernix",
  "Xenonova",
  "Vortexia",
  "Orionis",
  "Solara",
  "Nebulaflux",
  "Hydronix",
  "Titanus",
  "Erek",
  "Sven",
  "Tetsu",
  "Tetsuo",
  "Regal",
  "Gregal",
  "Greg",
  "Zui",
  "Ghostman",
  "Mango",
  "Vanilla",
  "Chocola",
  "Gandalf",
  "Sven",
  "Frog",
  "Froglord",
  "Frog-sama",
  "Frog-chan",
  "Nuki",
  "Mai",
  "Rhag",
  "Ein",
  "Potet",
  "Takoyaki",
  "Swimfan",
  "Darky",
  "Azrael",
  "Alimede",
  "Goro",
  "Speedii",
  "John",
  "Xiaoyu",
  "Kazuya",
  "Steve",
  "Teemo",
  "Jin",
  "Heihachi",
  "Azusa",
  "Tsubaki",
  "Miyamoto",
  "Dwayne",
  "Keitaro",
  "Vaz",
  "Kad",
  "Kunzok",
  "Ronkak",
  "Kamkaz",
  "Griefdelver",
  "Fangbrewer",
  "Soredripper",
  "Gloomstrike",
  "Giantsnout",
  "Sludgelegs",
  "Gunkchewer",
  "Gunkdrooler",
  "Slimesorrow",
  "Bandyg, The Voiceless One",
  "Frudrayn, The Adorable",
  "Frinus, The Tyrant",
  "Zievoit, The Clever",
  "Dorsis, The Hungry",
  "Berlalth, The Squeeler",
  "Chiossenus, The Fast One",
  "Jaro",
  "Aerav",
  "Zaid",
  "Harvel",
  "Cyrox",
  "Sagrun",
  "Svila",
  "Hlald",
  "Hlaldana",
  "Squidnuts",
  "Treesucker",
  "Slarmlicker",
  "Gitsmearer",
  "Frubfrub",
  "Berrychomper",
  "Hypodorrhurkel",
  "Hexapselchidviol",
  "Pyppeennolpid",
  "Fistfinger",
  "Crulzum Simplemaw",
  "Meri-s-ankh",
  "Nen-sala",
  "Khas-khem",
  "Gloomsnout",
  "Smokemouth",
  "Animeh",
  "Mort",
  "Chime",
  "Omega",
  "Cada",
  "Fowle",
  "Ingi",
  "Aquira",
  "Dune",
  "Mustard",
  "Ketchup",
  "Chuck",
  "Pugs",
  "Biggie",
  "Creep",
  "Frosty",
  "Q'zityuki",
  "M'sottu",
  "B'tchinsu",
  "Whiskers",
  "Fluff",
  "Cuddles",
  "Mohawk",
  "Hina",
  "Eimi",
  "Akari",
  "Junko",
  "Tsurugi",
  "Sora",
  "Yuuto",
  "Yamato",
  "The Red Gentleman",
  "The Headless Necromancer",
  "The Brown Force"
];

export const OBJECTS = [
  "Lumina's Embrace",
  "Ethereal Echo",
  "Aegis of Eternity",
  "Celestial Whisper",
  "Arcane Nexus",
  "Echoes of Solitude",
  "Astral Elixir",
  "Shroud of Shadows",
  "Resonance Orb",
  "Nexus of Sorrow",
  "Timeless Relic",
  "Midnight Mirage",
  "Aeon's Prism",
  "Veil of Dreams",
  "The Silent Key",
  "Voidheart",
  "Quantum Echo",
  "Nebula's Song",
  "Ethereal Cascade",
  "Eternal Echoes",
  "Quantum Resonator",
  "Warp Nexus",
  "Thunderbang",
  "Plasmic Capacitor",
  "Graviton Lens",
  "Temporal Anchor",
  "Singularity Core",
  "Dreambang",
  "The Radiant Existence Butcher",
  "Fusion Cascade",
  "Solaris Prism",
  "Electrum Node",
  "Unmaker of Realms",
  "The Veiled Eroder",
  "Void Harmonizer",
  "Flux Conduit",
  "Hayu",
  "Nebula Whisperer",
  "Tachyon Relay",
  "Particle Infuser",
  "The Shrouded Smirk",
  "The Crimson Tiger",
  "The Tranquil Crane",
  "The Unheard Snake",
  "The Mystic Mind",
  "Adma",
  "Dhivyuswa",
  "Khutholwas",
  "Sziscarzesh",
  "Idikke",
  "Chazorhix",
  "Tharhisheel",
  "Varonul",
  "Guoginleif",
  "Hlahylde",
  "Hjotha",
  "Bane of Heaven",
  "The Immortal Testaments",
  "The Codex of Purdarr",
  "The Effigy Testaments",
  "The Saints of Ahna",
  "The Book of Children",
  "Laws of the Lost",
  "The Agate Petal",
  "The Infinite Poem",
  "The Parallel Seal",
  "The Earnest Star",
  "Reinforced Magnet Mobilizer",
  "Gizmatic Broadcast Transformer",
  "Mimic Maximizer",
  "Strife Encrypter",
  "The Webbed Disk",
  "The Crimson Saucer",
  "The Branch of Thessalodge",
  "Coldheart",
  "Moonshadow",
  "Temperance"
];

export const PLACES = [
  "Grand Oak Athenaeum",
  "Cypress Beacon",
  "The Motionless Expanse",
  "Finia",
  "Scuglass",
  "The Peaceful Elephant",
  "The Orc Chasm",
  "The Tides of Pontawa",
  "The Depraved Deep",
  "The Forbidden Forest",
  "Crypt of the Shrouded Legion",
  "The Bloomerang",
  "Shrine of Passion",
  "The Cerulean Sanctum",
  "The Angelic Rock",
  "The Ivory Pillar",
  "Soothill",
  "Nozalix",
  "Silverwood",
  "Grand Plains",
  "Horizon",
  "Peace River",
  "Waterless Borderlands",
  "Arid Wastes",
  "The Naked Wilds",
  "Mirrorpool",
  "The Cycle Obelisk",
  "The Tower of Xuzyxi",
  "The Skeletal Tower",
  "The Inverted Pillar",
  "The Hollow Bridge",
  "The Glistening Pass",
  "Azza",
  "Xez'ra",
  "The Torment Dominion",
  "The Conflagration",
  "Chakra",
  "The Bed of Roses",
  "Wriggle Room",
  "Ironforge",
  "Serpent's Coil",
  "Dragonspire",
  "Emberfall",
  "Tera",
  "Halitus",
  "Violet Hill",
  "Ahlan",
  "Spritecell",
  "Taera"
];

export const VOICES = ["normal", "absurdist", "heavily accented"]

export const GOALS = [
  "is preparing to enter {Place}, the domain of the great dragon-lord {Person} and their demonic servants {Person} and {Person}, to try to retrieve a treasure called {Object} and as much loot as possible.",
  "is trying to intercept a clandestine but heavily protected shipment, allegedly containing an item called {Object}, sent by an antagonist named {Person} and escorted by {Person}.",
  "has just arrived on a mission to gather incriminating information about {Person}, the lord of this place, as well as an unknown entity called {Object}, and if all goes well, hard evidence of the connection between the two.",
  "is in the middle of a battle, but has lost their companions {Person}, {Person}, and {Person}, and is desperately trying to find them.",
  "is attempting to escape a location called {Place} with their family heirloom, {Object}, which must be kept away from the dark lord {Person} at all costs.",
  "is an assassin who is attempting to take out {Person}, {Person}, and {Person} without anybody noticing their presence.",
  "has just walked into {Place}, a magical emporium run by {Person}, where they see the magical artifact {Object} on display. The player is pretty sure the proprietor does not know what the object is, but they also stubbornly insist it's not for sale. The player is trying to leave the store with this item one way or the other, but must beware of the guards, {Person} and {Person}.",
  "has just walked into the infamous gambling den, {Place}, having been hired to retrieve an object called {Object} from the crime lord {Person}, which was lost by {Person} in a bet. The player can try to win the object back or retrieve it through other means, but must beware of the heavy security and the dangerous bouncer {Person}.",
  "is trying to find a way to {Place}, but is unable to open a portal, and time is running out. The player has {Object}, {Object}, {Object}, and {Object}, but must find a way to combine their powers to open the portal within the hour or all is lost."
];

export const MIXINS_COMMON = [
  "cats",
  "trees",
  "vehicles",
  "dogs",
  "chickens",
  "rats",
  "fire",
  "sewers",
  "cellar",
  "tavern",
  "explosions",
  "music",
  "rabbits",
  "rings",
  "ancient spells",
  "poison",
  "a pit trap",
  "a booby trapped object",
  "snakes",
  "meat",
  "a library",
  "heavy machinery",
  "bombs",
  "the sun",
  "ancient technology",
  "a curse",
  "potions",
  "a very tall building",
  "frogs",
  "jewels",
  "swords",
  "guns",
  "heavy weapons",
  "robots or constructs",
  "a party",
  "a religious building"
];

export const MIXINS_RARE = [
  "pants",
  "salt",
  "yams",
  "zoo",
  "cows",
  "ravers",
  "maids",
  "butlers",
  "a magical tank",
  "Hatsune Miku",
  "cacti",
  "salt"
];
